// Vendored snapshot of the DnD Music Guide
// (https://rayzold.github.io/crystalforge/DND_MUSIC_GUIDE.html) used to
// one-click seed the References panel. Vendored rather than fetched at
// runtime so:
//   - The panel works offline.
//   - The data shape is locked in source (no surprise schema drift if
//     the upstream guide changes its HTML).
//   - Re-importing is a deliberate code update, not a silent overwrite.
//
// Re-vendor by re-fetching the guide and running the same extraction.
// Snapshot dated 2026-06-21, 70 entries across 9 mood categories.
//
// The URLs are search-result links (the form the guide itself uses) —
// they redirect the user to the platform's search rather than a
// specific track. That's deliberate: it stays robust if a video gets
// taken down or a track gets re-released.

import type { TrackReference } from "@mc/data";

export type GuideSeedEntry = Omit<TrackReference, "addedAt" | "owned"> & {
  /** Stable id keyed to the guide's row number so re-running the
   *  import is idempotent (the repo's INSERT OR IGNORE keys on this). */
  id: string;
};

export const DND_MUSIC_GUIDE_SEEDS: ReadonlyArray<GuideSeedEntry> = [
  // ── Boss Battle ──────────────────────────────────────────────────────
  { id: "dnd-guide-001", title: "One Winged Angel", artist: "Nobuo Uematsu", category: "Boss Battle", notes: "The definitive villain theme — Latin choir.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=One+Winged+Angel+Nobuo+Uematsu+Final+Fantasy+VII", spotifyUrl: "https://open.spotify.com/search/One+Winged+Angel+Nobuo+Uematsu", source: "dnd-music-guide" },
  { id: "dnd-guide-002", title: "O Fortuna", artist: "Carl Orff", category: "Boss Battle", notes: "Fate crushing the party; a god descending.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=O+Fortuna+Carl+Orff+Carmina+Burana", spotifyUrl: "https://open.spotify.com/search/O+Fortuna+Carmina+Burana+Carl+Orff", source: "dnd-music-guide" },
  { id: "dnd-guide-003", title: "Battle with the Colossus", artist: "Kow Otani", category: "Boss Battle", notes: "Massive creature requiring outsmarting.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Battle+with+the+Colossus+Shadow+of+the+Colossus+Kow+Otani", spotifyUrl: "https://open.spotify.com/search/Battle+with+the+Colossus+Shadow+of+the+Colossus", source: "dnd-music-guide" },
  { id: "dnd-guide-004", title: "You Will Know Our Names", artist: "ACE+", category: "Boss Battle", notes: "Relentless escalating boss phases.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=You+Will+Know+Our+Names+Xenoblade+Chronicles", spotifyUrl: "https://open.spotify.com/search/You+Will+Know+Our+Names+Xenoblade+Chronicles", source: "dnd-music-guide" },
  { id: "dnd-guide-005", title: "Dancing Mad", artist: "Nobuo Uematsu", category: "Boss Battle", notes: "17-minute organ epic; chaos deity.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Dancing+Mad+Final+Fantasy+VI+Nobuo+Uematsu", spotifyUrl: "https://open.spotify.com/search/Dancing+Mad+Final+Fantasy+VI", source: "dnd-music-guide" },
  { id: "dnd-guide-006", title: "MEGALOVANIA", artist: "Toby Fox", category: "Boss Battle", notes: "Villain stops playing games.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=MEGALOVANIA+Toby+Fox+Undertale", spotifyUrl: "https://open.spotify.com/search/MEGALOVANIA+Undertale+Toby+Fox", source: "dnd-music-guide" },
  { id: "dnd-guide-007", title: "Calamity Ganon Battle", artist: "Manaka Kataoka", category: "Boss Battle", notes: "Corrupted entity; transformed threat.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Calamity+Ganon+Battle+Zelda+Breath+of+the+Wild", spotifyUrl: "https://open.spotify.com/search/Calamity+Ganon+Battle+Breath+of+the+Wild", source: "dnd-music-guide" },
  { id: "dnd-guide-008", title: "Cleric Beast", artist: "Ryan Amon", category: "Boss Battle", notes: "Frenzied church choir; sacred monster.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Cleric+Beast+Bloodborne+Ryan+Amon", spotifyUrl: "https://open.spotify.com/search/Cleric+Beast+Bloodborne", source: "dnd-music-guide" },

  // ── Suspense ─────────────────────────────────────────────────────────
  { id: "dnd-guide-009", title: "Requiem for a Dream", artist: "Clint Mansell", category: "Suspense", notes: "Spiraling dread; time running out.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Requiem+for+a+Dream+Clint+Mansell+Lux+Aeterna", spotifyUrl: "https://open.spotify.com/search/Requiem+for+a+Dream+Clint+Mansell", source: "dnd-music-guide" },
  { id: "dnd-guide-010", title: "Jaws Theme", artist: "John Williams", category: "Suspense", notes: "Unseen approaching threat.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Jaws+Theme+John+Williams", spotifyUrl: "https://open.spotify.com/search/Jaws+Theme+John+Williams", source: "dnd-music-guide" },
  { id: "dnd-guide-011", title: "Time", artist: "Hans Zimmer", category: "Suspense", notes: "Slow-burn revelation; closing countdown.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Time+Hans+Zimmer+Inception+OST", spotifyUrl: "https://open.spotify.com/search/Time+Hans+Zimmer+Inception", source: "dnd-music-guide" },
  { id: "dnd-guide-012", title: "In the Hall of the Mountain King", artist: "Edvard Grieg", category: "Suspense", notes: "Creeping tempo building to chaos.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=In+the+Hall+of+the+Mountain+King+Grieg", spotifyUrl: "https://open.spotify.com/search/In+the+Hall+of+the+Mountain+King+Grieg", source: "dnd-music-guide" },
  { id: "dnd-guide-013", title: "Toccata and Fugue in D Minor", artist: "J.S. Bach", category: "Suspense", notes: "Ancient evil; crypt/cathedral.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Toccata+and+Fugue+in+D+Minor+Bach+organ", spotifyUrl: "https://open.spotify.com/search/Toccata+and+Fugue+D+minor+Bach", source: "dnd-music-guide" },
  { id: "dnd-guide-014", title: "Tension", artist: "Akira Yamaoka", category: "Suspense", notes: "Industrial ambience; unseen watchers.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Tension+Akira+Yamaoka+Silent+Hill+2", spotifyUrl: "https://open.spotify.com/search/Tension+Akira+Yamaoka+Silent+Hill+2", source: "dnd-music-guide" },
  { id: "dnd-guide-015", title: "Dread (Metroid Prime)", artist: "Kenji Yamamoto", category: "Suspense", notes: "Alien menace in confined spaces.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Dread+Metroid+Prime+OST+Kenji+Yamamoto", spotifyUrl: "https://open.spotify.com/search/Metroid+Prime+Dread+OST", source: "dnd-music-guide" },

  // ── Mystery ──────────────────────────────────────────────────────────
  { id: "dnd-guide-016", title: "X-Files Theme", artist: "Mark Snow", category: "Mystery", notes: "Eerie and procedural; investigation.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=X-Files+Theme+Mark+Snow", spotifyUrl: "https://open.spotify.com/search/X-Files+Theme+Mark+Snow", source: "dnd-music-guide" },
  { id: "dnd-guide-017", title: "Twin Peaks Theme", artist: "Angelo Badalamenti", category: "Mystery", notes: "Town wrongness; beauty hiding something.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Twin+Peaks+Theme+Angelo+Badalamenti", spotifyUrl: "https://open.spotify.com/search/Twin+Peaks+Theme+Angelo+Badalamenti", source: "dnd-music-guide" },
  { id: "dnd-guide-018", title: "Kingdom of Zeal", artist: "Yasunori Mitsuda", category: "Mystery", notes: "Utopia hiding moral rot.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Kingdom+of+Zeal+Chrono+Trigger+Yasunori+Mitsuda", spotifyUrl: "https://open.spotify.com/search/Kingdom+of+Zeal+Chrono+Trigger", source: "dnd-music-guide" },
  { id: "dnd-guide-019", title: "Professor Layton Main Theme", artist: "Tomohito Nishiura", category: "Mystery", notes: "Curious puzzle-solving; cozy.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Professor+Layton+Main+Theme+Tomohito+Nishiura", spotifyUrl: "https://open.spotify.com/search/Professor+Layton+Main+Theme", source: "dnd-music-guide" },
  { id: "dnd-guide-020", title: "Dark World", artist: "Koji Kondo", category: "Mystery", notes: "Corrupted mirror; shadow realm.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Dark+World+Zelda+Link+to+the+Past+Koji+Kondo", spotifyUrl: "https://open.spotify.com/search/Dark+World+Zelda+A+Link+to+the+Past", source: "dnd-music-guide" },
  { id: "dnd-guide-021", title: "Dearly Beloved", artist: "Yoko Shimomura", category: "Mystery", notes: "Melancholic; revelation aftermath.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Dearly+Beloved+Yoko+Shimomura+Kingdom+Hearts", spotifyUrl: "https://open.spotify.com/search/Dearly+Beloved+Kingdom+Hearts+Yoko+Shimomura", source: "dnd-music-guide" },
  { id: "dnd-guide-022", title: "Myst Main Theme", artist: "Robyn Miller", category: "Mystery", notes: "Abandoned place; mysterious mechanisms.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Myst+Main+Theme+Robyn+Miller+1993", spotifyUrl: "https://open.spotify.com/search/Myst+Main+Theme", source: "dnd-music-guide" },
  { id: "dnd-guide-023", title: "Hedwig's Theme", artist: "John Williams", category: "Mystery", notes: "Magic entering everyday life.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Hedwig%27s+Theme+John+Williams+Harry+Potter", spotifyUrl: "https://open.spotify.com/search/Hedwig%27s+Theme+John+Williams+Harry+Potter", source: "dnd-music-guide" },
  { id: "dnd-guide-024", title: "A Window to the Past", artist: "John Williams", category: "Mystery", notes: "Discovering old history.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=A+Window+to+the+Past+John+Williams+Prisoner+of+Azkaban", spotifyUrl: "https://open.spotify.com/search/A+Window+to+the+Past+John+Williams+Harry+Potter", source: "dnd-music-guide" },

  // ── Horror ───────────────────────────────────────────────────────────
  { id: "dnd-guide-025", title: "Halloween Theme", artist: "John Carpenter", category: "Horror", notes: "Relentless slasher threat.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Halloween+Theme+John+Carpenter+1978", spotifyUrl: "https://open.spotify.com/search/Halloween+Theme+John+Carpenter", source: "dnd-music-guide" },
  { id: "dnd-guide-026", title: "Tubular Bells", artist: "Mike Oldfield", category: "Horror", notes: "Childhood-tinged wrongness; possession.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Tubular+Bells+Mike+Oldfield+Exorcist", spotifyUrl: "https://open.spotify.com/search/Tubular+Bells+Mike+Oldfield", source: "dnd-music-guide" },
  { id: "dnd-guide-027", title: "Don't Be Afraid", artist: "Akira Yamaoka", category: "Horror", notes: "Dissonant ambience; reality distortion.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Don%27t+Be+Afraid+Akira+Yamaoka+Silent+Hill+2", spotifyUrl: "https://open.spotify.com/search/Dont+Be+Afraid+Akira+Yamaoka+Silent+Hill+2", source: "dnd-music-guide" },
  { id: "dnd-guide-028", title: "It Follows OST", artist: "Disasterpeace", category: "Horror", notes: "Synth dread; always approaching.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=It+Follows+OST+Disasterpeace", spotifyUrl: "https://open.spotify.com/search/It+Follows+OST+Disasterpeace", source: "dnd-music-guide" },
  { id: "dnd-guide-029", title: "The Thing Main Theme", artist: "Ennio Morricone", category: "Horror", notes: "Paranoia; shapeshifter scenario.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=The+Thing+Main+Theme+Ennio+Morricone+1982", spotifyUrl: "https://open.spotify.com/search/The+Thing+Theme+Ennio+Morricone", source: "dnd-music-guide" },
  { id: "dnd-guide-030", title: "Crimson Head (Arrange)", artist: "Capcom Sound Team", category: "Horror", notes: "Confined space dread; resource scarcity.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Resident+Evil+Crimson+Head+theme+OST", spotifyUrl: "https://open.spotify.com/search/Resident+Evil+Crimson+Head", source: "dnd-music-guide" },
  { id: "dnd-guide-031", title: "Amnesia: The Dark Descent OST", artist: "Mikko Tarmia", category: "Horror", notes: "Formless dread; no weapons/options.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Amnesia+The+Dark+Descent+OST+Mikko+Tarmia", spotifyUrl: "https://open.spotify.com/search/Amnesia+Dark+Descent+OST+Mikko+Tarmia", source: "dnd-music-guide" },

  // ── Tavern & City ────────────────────────────────────────────────────
  { id: "dnd-guide-032", title: "Flagon's Dragon", artist: "Inon Zur", category: "Tavern & City", notes: "Definitive fantasy tavern track; lute/fiddle.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Flagon%27s+Dragon+Dragon+Age+Origins+Inon+Zur", spotifyUrl: "https://open.spotify.com/search/Flagon%27s+Dragon+Dragon+Age+Origins", source: "dnd-music-guide" },
  { id: "dnd-guide-033", title: "Tristram Village", artist: "Matt Uelmen", category: "Tavern & City", notes: "Melancholy; safe surface/dark rumors.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Tristram+Village+Matt+Uelmen+Diablo+1996", spotifyUrl: "https://open.spotify.com/search/Tristram+Village+Diablo", source: "dnd-music-guide" },
  { id: "dnd-guide-034", title: "The Valley Comes Alive", artist: "ConcernedApe", category: "Tavern & City", notes: "Cheerful pastoral village.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=The+Valley+Comes+Alive+Stardew+Valley", spotifyUrl: "https://open.spotify.com/search/The+Valley+Comes+Alive+Stardew+Valley", source: "dnd-music-guide" },
  { id: "dnd-guide-035", title: "Witcher 3 Tavern Music", artist: "Marcin Przybyłowicz", category: "Tavern & City", notes: "Medieval Slavic folk; rowdy inn.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Witcher+3+Tavern+Music+Marcin+Przybylowicz", spotifyUrl: "https://open.spotify.com/search/Witcher+3+Tavern+Music", source: "dnd-music-guide" },
  { id: "dnd-guide-036", title: "Bag End (Shire Theme)", artist: "Howard Shore", category: "Tavern & City", notes: "Hobbit comfort; safe settlement.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Bag+End+Shire+Theme+Howard+Shore+Lord+of+the+Rings", spotifyUrl: "https://open.spotify.com/search/Bag+End+Shire+Theme+Howard+Shore", source: "dnd-music-guide" },
  { id: "dnd-guide-037", title: "Midgar (City Theme)", artist: "Nobuo Uematsu", category: "Tavern & City", notes: "Industrial metropolis; inequality.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Midgar+City+Theme+Final+Fantasy+VII+Nobuo+Uematsu", spotifyUrl: "https://open.spotify.com/search/Midgar+Theme+Final+Fantasy+VII", source: "dnd-music-guide" },
  { id: "dnd-guide-038", title: "The Wolven Storm (Priscilla's Song)", artist: "Marcin Przybyłowicz", category: "Tavern & City", notes: "Bardic performance; bittersweet mood.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=The+Wolven+Storm+Priscilla%27s+Song+Witcher+3", spotifyUrl: "https://open.spotify.com/search/The+Wolven+Storm+Priscilla%27s+Song+Witcher+3", source: "dnd-music-guide" },

  // ── Weather & Ambience ───────────────────────────────────────────────
  { id: "dnd-guide-039", title: "Clair de Lune", artist: "Claude Debussy", category: "Weather & Ambience", notes: "Moonlit stillness; quiet night.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Clair+de+Lune+Debussy+piano", spotifyUrl: "https://open.spotify.com/search/Clair+de+Lune+Debussy", source: "dnd-music-guide" },
  { id: "dnd-guide-040", title: "La Mer", artist: "Claude Debussy", category: "Weather & Ambience", notes: "Ocean travel; vast natural space.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=La+Mer+Debussy+orchestra", spotifyUrl: "https://open.spotify.com/search/La+Mer+Debussy", source: "dnd-music-guide" },
  { id: "dnd-guide-041", title: "City of Tears (Waterways)", artist: "Christopher Larkin", category: "Weather & Ambience", notes: "Ruined flooded city; perpetual rain.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=City+of+Tears+Hollow+Knight+Christopher+Larkin", spotifyUrl: "https://open.spotify.com/search/City+of+Tears+Hollow+Knight", source: "dnd-music-guide" },
  { id: "dnd-guide-042", title: "Snowdin Town", artist: "Toby Fox", category: "Weather & Ambience", notes: "Frosted peaceful snow settlement.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Snowdin+Town+Toby+Fox+Undertale", spotifyUrl: "https://open.spotify.com/search/Snowdin+Town+Undertale+Toby+Fox", source: "dnd-music-guide" },
  { id: "dnd-guide-043", title: "Far Horizons", artist: "Jeremy Soule", category: "Weather & Ambience", notes: "Wordless soprano; mountain summit/dawn.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Far+Horizons+Jeremy+Soule+Skyrim", spotifyUrl: "https://open.spotify.com/search/Far+Horizons+Skyrim+Jeremy+Soule", source: "dnd-music-guide" },
  { id: "dnd-guide-044", title: "Storm (Journey OST)", artist: "Austin Wintory", category: "Weather & Ambience", notes: "Desert/wasteland traversal.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Storm+Austin+Wintory+Journey+OST", spotifyUrl: "https://open.spotify.com/search/Storm+Austin+Wintory+Journey", source: "dnd-music-guide" },
  { id: "dnd-guide-045", title: "Pastoral Symphony — Storm (Mvt. 4)", artist: "Ludwig van Beethoven", category: "Weather & Ambience", notes: "Literal orchestral thunderstorm.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Beethoven+Pastoral+Symphony+Storm+Movement+4", spotifyUrl: "https://open.spotify.com/search/Beethoven+Pastoral+Symphony+Movement+4", source: "dnd-music-guide" },

  // ── Combat ───────────────────────────────────────────────────────────
  { id: "dnd-guide-046", title: "Gerudo Valley", artist: "Koji Kondo", category: "Combat", notes: "Flamenco urgency; swift skirmish.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Gerudo+Valley+Koji+Kondo+Zelda+Ocarina+of+Time", spotifyUrl: "https://open.spotify.com/search/Gerudo+Valley+Zelda+Ocarina+of+Time", source: "dnd-music-guide" },
  { id: "dnd-guide-047", title: "He's a Pirate", artist: "Hans Zimmer", category: "Combat", notes: "Swashbuckling; daring/fun fight.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=He%27s+a+Pirate+Hans+Zimmer+Pirates+of+the+Caribbean", spotifyUrl: "https://open.spotify.com/search/He%27s+a+Pirate+Hans+Zimmer+Pirates+of+the+Caribbean", source: "dnd-music-guide" },
  { id: "dnd-guide-048", title: "Saber's Edge", artist: "Masashi Hamauzu", category: "Combat", notes: "Mechanical drive; efficient danger.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Saber%27s+Edge+Masashi+Hamauzu+Final+Fantasy+XIII", spotifyUrl: "https://open.spotify.com/search/Saber%27s+Edge+Final+Fantasy+XIII", source: "dnd-music-guide" },
  { id: "dnd-guide-049", title: "Combat Theme (Halo CE)", artist: "Martin O'Donnell", category: "Combat", notes: "Gregorian chant; mid-tier encounter.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Halo+Combat+Evolved+Combat+Theme+Martin+O%27Donnell", spotifyUrl: "https://open.spotify.com/search/Halo+Combat+Evolved+Theme", source: "dnd-music-guide" },
  { id: "dnd-guide-050", title: "Gwyn, Lord of Cinder", artist: "Motoi Sakuraba", category: "Combat", notes: "Solo piano; broken/tragic king.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Gwyn+Lord+of+Cinder+Dark+Souls+Motoi+Sakuraba", spotifyUrl: "https://open.spotify.com/search/Gwyn+Lord+of+Cinder+Dark+Souls", source: "dnd-music-guide" },
  { id: "dnd-guide-051", title: "The Decisive Battle", artist: "Nobuo Uematsu", category: "Combat", notes: "Urgent JRPG energy; mid-stakes group.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=The+Decisive+Battle+Nobuo+Uematsu+Final+Fantasy+VI", spotifyUrl: "https://open.spotify.com/search/The+Decisive+Battle+Final+Fantasy+VI", source: "dnd-music-guide" },
  { id: "dnd-guide-052", title: "Tempest", artist: "ACE+", category: "Combat", notes: "Timed encounter; desperate retreat.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Tempest+Xenoblade+Chronicles+ACE%2B", spotifyUrl: "https://open.spotify.com/search/Tempest+Xenoblade+Chronicles", source: "dnd-music-guide" },

  // ── Sorrow & Loss ────────────────────────────────────────────────────
  { id: "dnd-guide-053", title: "To Zanarkand", artist: "Nobuo Uematsu", category: "Sorrow & Loss", notes: "Farewell/sacrifice; something ending.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=To+Zanarkand+Nobuo+Uematsu+Final+Fantasy+X", spotifyUrl: "https://open.spotify.com/search/To+Zanarkand+Final+Fantasy+X", source: "dnd-music-guide" },
  { id: "dnd-guide-054", title: "Aerith's Theme", artist: "Nobuo Uematsu", category: "Sorrow & Loss", notes: "Loss of someone irreplaceable; NPC death.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Aerith%27s+Theme+Nobuo+Uematsu+Final+Fantasy+VII", spotifyUrl: "https://open.spotify.com/search/Aerith%27s+Theme+Final+Fantasy+VII", source: "dnd-music-guide" },
  { id: "dnd-guide-055", title: "Ezio's Family", artist: "Jesper Kyd", category: "Sorrow & Loss", notes: "Wordless soprano; permanent change.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Ezio%27s+Family+Jesper+Kyd+Assassin%27s+Creed+II", spotifyUrl: "https://open.spotify.com/search/Ezio%27s+Family+Jesper+Kyd+Assassin%27s+Creed+2", source: "dnd-music-guide" },
  { id: "dnd-guide-056", title: "Hymn of the Fayth", artist: "Nobuo Uematsu", category: "Sorrow & Loss", notes: "Sacrificial prayer; dead civilization.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Hymn+of+the+Fayth+Final+Fantasy+X+Nobuo+Uematsu", spotifyUrl: "https://open.spotify.com/search/Hymn+of+the+Fayth+Final+Fantasy+X", source: "dnd-music-guide" },
  { id: "dnd-guide-057", title: "The Last of Us Main Theme", artist: "Gustavo Santaolalla", category: "Sorrow & Loss", notes: "Sparse guitar; aftermath/graves.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=The+Last+of+Us+Main+Theme+Gustavo+Santaolalla", spotifyUrl: "https://open.spotify.com/search/The+Last+of+Us+Main+Theme+Santaolalla", source: "dnd-music-guide" },
  { id: "dnd-guide-058", title: "Shadow World", artist: "Jeremy Soule", category: "Sorrow & Loss", notes: "Quiet mourning; funeral scene.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Shadow+World+Jeremy+Soule+Dragon+Age+Origins", spotifyUrl: "https://open.spotify.com/search/Shadow+World+Dragon+Age+Origins+Jeremy+Soule", source: "dnd-music-guide" },
  { id: "dnd-guide-059", title: "Weight of the World (Instrumental)", artist: "Keiichi Okabe", category: "Sorrow & Loss", notes: "Exhausted beauty; costly victory.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Weight+of+the+World+instrumental+NieR+Automata+Keiichi+Okabe", spotifyUrl: "https://open.spotify.com/search/Weight+of+the+World+Nier+Automata", source: "dnd-music-guide" },
  { id: "dnd-guide-060", title: "Misty Mountains Cold", artist: "Richard Armitage & Cast", category: "Sorrow & Loss", notes: "Dwarf song; home lost to dragon.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Misty+Mountains+Cold+The+Hobbit+Richard+Armitage+dwarves", spotifyUrl: "https://open.spotify.com/search/Misty+Mountains+Cold+The+Hobbit", source: "dnd-music-guide" },
  { id: "dnd-guide-061", title: "Leaving Hogwarts", artist: "John Williams", category: "Sorrow & Loss", notes: "Bittersweet departure; cannot return.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Leaving+Hogwarts+John+Williams+Harry+Potter+Sorcerer%27s+Stone", spotifyUrl: "https://open.spotify.com/search/Leaving+Hogwarts+John+Williams+Harry+Potter", source: "dnd-music-guide" },
  { id: "dnd-guide-062", title: "Dobby's Farewell", artist: "Alexandre Desplat", category: "Sorrow & Loss", notes: "Beloved companion death; short/sharp.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Dobby%27s+Farewell+Alexandre+Desplat+Deathly+Hallows", spotifyUrl: "https://open.spotify.com/search/Dobby%27s+Farewell+Alexandre+Desplat+Harry+Potter", source: "dnd-music-guide" },

  // ── Triumph & Celebration ────────────────────────────────────────────
  { id: "dnd-guide-063", title: "Also Sprach Zarathustra (Sunrise)", artist: "Richard Strauss", category: "Triumph & Celebration", notes: "Monumental achievement; prophecy fulfilled.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Also+Sprach+Zarathustra+Richard+Strauss+sunrise", spotifyUrl: "https://open.spotify.com/search/Also+Sprach+Zarathustra+Strauss", source: "dnd-music-guide" },
  { id: "dnd-guide-064", title: "Ode to Joy (Orchestral)", artist: "Ludwig van Beethoven", category: "Triumph & Celebration", notes: "Grand coronation; war liberation.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Ode+to+Joy+Beethoven+Symphony+9+orchestra", spotifyUrl: "https://open.spotify.com/search/Ode+to+Joy+Beethoven+Symphony+9", source: "dnd-music-guide" },
  { id: "dnd-guide-065", title: "Fellowship of the Ring Theme", artist: "Howard Shore", category: "Triumph & Celebration", notes: "Bittersweet triumph; costly victory.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Fellowship+of+the+Ring+Theme+Howard+Shore+Lord+of+the+Rings", spotifyUrl: "https://open.spotify.com/search/Fellowship+of+the+Ring+Theme+Howard+Shore", source: "dnd-music-guide" },
  { id: "dnd-guide-066", title: "Star Wars Main Theme", artist: "John Williams", category: "Triumph & Celebration", notes: "Heroic/optimistic; recognizable.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Star+Wars+Main+Theme+John+Williams", spotifyUrl: "https://open.spotify.com/search/Star+Wars+Main+Theme+John+Williams", source: "dnd-music-guide" },
  { id: "dnd-guide-067", title: "Victory Fanfare", artist: "Nobuo Uematsu", category: "Triumph & Celebration", notes: "Short/playful post-fight beat.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Victory+Fanfare+Final+Fantasy+Nobuo+Uematsu", spotifyUrl: "https://open.spotify.com/search/Victory+Fanfare+Final+Fantasy", source: "dnd-music-guide" },
  { id: "dnd-guide-068", title: "Apotheosis", artist: "Austin Wintory", category: "Triumph & Celebration", notes: "Wordless ascent; transcendent ending.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Apotheosis+Austin+Wintory+Journey", spotifyUrl: "https://open.spotify.com/search/Apotheosis+Journey+Austin+Wintory", source: "dnd-music-guide" },
  { id: "dnd-guide-069", title: "Aria di Mezzo Carattere (Orchestral)", artist: "Nobuo Uematsu", category: "Triumph & Celebration", notes: "Opera; celebration with loss awareness.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Aria+di+Mezzo+Carattere+Final+Fantasy+VI+Nobuo+Uematsu", spotifyUrl: "https://open.spotify.com/search/Aria+di+Mezzo+Carattere+Final+Fantasy+VI", source: "dnd-music-guide" },
  { id: "dnd-guide-070", title: "Harry's Wondrous World", artist: "John Williams", category: "Triumph & Celebration", notes: "Wonder/earned triumph; magical discovery.", url: null, youtubeUrl: "https://www.youtube.com/results?search_query=Harry%27s+Wondrous+World+John+Williams+Harry+Potter", spotifyUrl: "https://open.spotify.com/search/Harry%27s+Wondrous+World+John+Williams+Harry+Potter", source: "dnd-music-guide" },
];

/** Stable order in the source matches the guide's row numbers. */
export const DND_MUSIC_GUIDE_CATEGORIES = [
  "Boss Battle",
  "Suspense",
  "Mystery",
  "Horror",
  "Tavern & City",
  "Weather & Ambience",
  "Combat",
  "Sorrow & Loss",
  "Triumph & Celebration",
] as const;
